<?php

/**
 * @file
 * Contains bibcite_footnotes.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Implements hook_help().
 */
function bibcite_footnotes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bibcite_footnotes module.
    case 'help.page.bibcite_footnotes':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Inline footnote links for BibCite References') . '</p>';
      return $output;

    default:
  }
}

function bibcite_footnotes_preprocess_footnote_list(&$variables) {

  // Drupal 7 requires we use "render element" which just introduces a wrapper
  // around the old array.
  // $footnotes = $footnotes['footnotes'];
  // loop through the footnotes.
  $footnotes = $variables['footnotes'];
  $notes = [
    '#theme' => 'item_list',
    '#list_type' => 'ul',
    '#title' => 'Notes',
    '#attributes' => ['class' => 'footnotes'],
    '#wrapper_attributes' => ['class' => 'container'],
  ];

  $references= [
    '#theme' => 'item_list',
    '#list_type' => 'ul',
    '#title' => 'References',
    '#attributes' => ['class' => 'footnotes'],
    '#wrapper_attributes' => ['class' => 'container'],
  ];

  $view_builder = \Drupal::entityTypeManager()->getViewBuilder('bibcite_reference');

  foreach ($footnotes as $fn) {
    if (!is_array($fn['ref_id'])) {
      // Output normal footnote.
      $item = [
        '#id' => $fn['fn_id'],

      ];

      $url = Url::fromUserInput('#' . $fn['ref_id'], ['attributes' => ['id' => $fn['fn_id']]]);

//      $url->setOptions($link_options);

      $link = Link::fromTextAndUrl($fn['value'], $url);

      $link = $link->toString();


      preg_match('/\[bibcite_reference:(\d*)\]/', $fn['text'], $matches);
      $reference_entity_id = $matches[1];
      if (!empty($reference_entity_id)) {
        $reference_storage = \Drupal::entityTypeManager()
          ->getStorage('bibcite_reference')
          ->load($reference_entity_id);
        $item['#attributes'] = [
          'class' => ['footnote'],
        ];
        $build = $view_builder->view($reference_storage, 'citation');
        $render = render($build);

        $item['#markup'] = $link . ' ' . $render;
        $references['#items'] = $item;
      }
      else {
        $item['#markup'] = $link . ' ' . $fn['text'];

        $notes['#items'][] = $item;
      }
    }
    else {
      // Output footnote that has more than one reference to it in the body.
      // The only difference is to insert backlinks to all references.
      // Helper: we need to enumerate a, b, c...
      $abc = str_split("abcdefghijklmnopqrstuvwxyz");
      $i = 0;
      $item = [
        '#wrapper_attributes' => [
          'class' => "footnote",
          'id' => $fn['fn_id'],
        ],
        '#value' => [
          [
            '#type' => 'link',
            '#title' => $fn['value'],
            '#href' => "#" . $fn['ref_id'][0],
            '#attributes' => [
              '#class' => 'footnote-label',
            ],
          ],
        ],
      ];

      foreach ($fn['ref_id'] as $ref) {
        $item['#value'][] = [
          '#type' => 'link',
          '#title' => $abc[$i],
          '#href' => '#' . $ref,
          '#attributes' => [
            'class' => 'footnote-multi',
          ],
        ];
        $i++;
      }
      $item['#value'][] = $fn['text'];
      $references[] = $item;
    }

  }

  $variables['notes'] = $notes;
ksm($notes);
  $variables['references'] = $references;

}

/**
 * Implements hook_theme().
 */
function bibcite_footnotes_theme() {
  return [
    'bibcite_footnotes' => [
      'render element' => 'children',
    ],
  ];
}

function bibcite_footnotes_theme_registry_alter(&$theme_registry) {
  unset($theme_registry['footnote_list']['function']);
//  $theme_registry['footnote_list']['function'] = 'bibcite_footnotes_theme_footnote_list';
  $theme_registry['footnote_list']['path'] = drupal_get_path('module', 'bibcite_footnotes') . '/templates';
  $theme_registry['footnote_list']['template'] = 'footnote-list';
  $theme_registry['footnote_list']['variables']['notes'] = [];
  $theme_registry['footnote_list']['variables']['references'] = [];
  $theme_registry['footnote_list']['variables']['footnotes'] = [];
}

function bibcite_footnotes_theme_footnote_list($footnotes) {
  // @todo: change this ugly array for arguments in the function.
  $footnotes = $footnotes['footnotes']['#footnotes'];

  $notes = [
    '#theme' => 'item_list',
    '#list_type' => 'ul',
    '#title' => 'Notes',
    '#attributes' => ['class' => ''],
    '#wrapper_attributes' => ['class' => 'container'],
  ];

//  return drupal_render($content);
  $str = '<ul class="footnotes">';
  // Drupal 7 requires we use "render element" which just introduces a wrapper
  // around the old array.
  // $footnotes = $footnotes['footnotes'];
  // loop through the footnotes.
  $view_builder = \Drupal::entityTypeManager()->getViewBuilder('bibcite_reference');
  foreach ($footnotes as $fn) {
    if (!is_array($fn['ref_id'])) {
      // Output normal footnote.
      $str .= '<li class="footnote" id="' . $fn['fn_id'] . '"><a class="footnote-label" href="#' . $fn['ref_id'] . '">' . $fn['value'] . '.</a> ';
      preg_match('/\[bibcite_reference:(\d*)\]/', $fn['text'], $matches);
      $reference_entity_id = $matches[1];
      if (!empty($reference_entity_id)) {
        $reference_storage = \Drupal::entityTypeManager()
          ->getStorage('bibcite_reference')
          ->load($reference_entity_id);

        $build = $view_builder->view($reference_storage, 'citation');
        $render = render($build);

        $str .= $render . "</li>\n";
      }
      else {
        $str .= $fn['text'] . "</li>\n";
      }
    }
    else {
      // Output footnote that has more than one reference to it in the body.
      // The only difference is to insert backlinks to all references.
      // Helper: we need to enumerate a, b, c...
      $abc = str_split("abcdefghijklmnopqrstuvwxyz");
      $i = 0;

      $str .= '<li class="footnote" id="' . $fn['fn_id'] . '"><a href="#' . $fn['ref_id'][0] . '" class="footnote-label">' . $fn['value'] . '.</a> ';
      foreach ($fn['ref_id'] as $ref) {
        $str .= '<a class="footnote-multi" href="#' . $ref . '">' . $abc[$i] . '.</a> ';
        $i++;
      }
      $str .= $fn['text'] . "</li>\n";
    }
  }

  return $str;

}
